In [119]:
import numpy as np

In [120]:
array= np.array([1,2,3,4,5])

In [121]:
array2d=np.array([[1,2,3],[4,5,6]])
print(array2d)

[[1 2 3]
 [4 5 6]]


In [122]:
c=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    
    [
        [7,8,9],
        [11,11,11]
    ]
    ])

print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 11 11]]]


In [123]:
print(array.ndim)
print(array2d.ndim)
print(c.ndim)

1
2
3


In [124]:
a=np.empty([3,3])

print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [125]:
a=np.zeros([3,3])

print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [126]:
a=np.full([2,2], "Shakeel a")

print(a)

[['Shakeel a' 'Shakeel a']
 ['Shakeel a' 'Shakeel a']]


In [127]:
list=(1,2,3,4,5,6,7,8,9)

a=np.asarray(list)

print(list)
print(a)

(1, 2, 3, 4, 5, 6, 7, 8, 9)
[1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.arange(1,101).reshape(10,10)

print(a)

In [129]:
print(a[2])

[21 22 23 24 25 26 27 28 29 30]


In [130]:
print(a[:4,5])

[ 6 16 26 36]


In [131]:
print(a[:,:2])

[[ 1  2]
 [11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]
 [61 62]
 [71 72]
 [81 82]
 [91 92]]


In [148]:
print(a)

[[1 2]
 [3 4]]


In [146]:
a=np.arange(1,5).reshape(2,2)
b=np.arange(5,9).reshape(2,2)

print(a,)

print(b)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [134]:
c=np.concatenate((a,b))

print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [135]:
c=np.hstack((a,b))

print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [136]:
c=np.concatenate((a,b), axis=0)

print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [137]:
n=np.array([1,2,3,4,5], dtype='i')

print(a)

[[1 2]
 [3 4]]


In [138]:
b=a.copy()
x=b.view()
x[0]=5

print(x)

[[5 5]
 [3 4]]


In [147]:
m=np.arange(1,10).reshape(3,3)

x=a.shape
print(x)

(2, 2)


In [164]:
a=np.arange(1,101).reshape(10,10)

print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [159]:
b=a.reshape(4,-1,25)
print(b)

[[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
    18  19  20  21  22  23  24  25]]

 [[ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42
    43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
    68  69  70  71  72  73  74  75]]

 [[ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
    93  94  95  96  97  98  99 100]]]


In [177]:
x=a[:1,0:9].reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [180]:
print(x.transpose())



[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [190]:
x=np.where(c%5==0)

print(x)

(array([2], dtype=int64), array([0], dtype=int64))


In [200]:
print(np.sort(a,axis=0))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
