In [42]:
import numpy as np
import pandas as pd



In [21]:
list=['Mango tree','Coconut tree','papaya tree','apple tree','banana tree','blackberry tree']
list[2]=' '
list[3]=' '
list[4]=' '

list.insert(0,'Neem tree')
list.insert(1,'peepal tree')

print(list)

string='banana tree'

Number=lambda x:x.count('n')

print(Number(string))



['Neem tree', 'peepal tree', 'Mango tree', 'Coconut tree', ' ', ' ', ' ', 'blackberry tree']
2


In [37]:
a='Amaan'
b=list[a]
dict={ x:y for x in a for y in a if x==y }

print(dict)

TypeError: list indices must be integers or slices, not str

In [31]:
string='Amaan'
count=0
for x in string:
    for y in string:
        if x==y:
            dict={x:count=count+1}
    count=0 
print(dict)



SyntaxError: invalid syntax (3614677182.py, line 6)

In [39]:
input_string = "Hello"
split_characters = list[input_string]
print(split_characters)


TypeError: list indices must be integers or slices, not str

In [59]:
series=pd.Series([4,7,-5,3,3.3])

print(series)

0    4.0
1    7.0
2   -5.0
3    3.0
4    3.3
dtype: float64


In [60]:
series.index=['d','b','a','c','e']

print(series)



d    4.0
b    7.0
a   -5.0
c    3.0
e    3.3
dtype: float64


In [61]:
min=series.min()
max=series.max()

print(min)

print(max)

-5.0
7.0


In [62]:
print(series.sort_values(ascending=0))

print(series.sort_values(ascending=1))

b    7.0
d    4.0
e    3.3
c    3.0
a   -5.0
dtype: float64
a   -5.0
c    3.0
e    3.3
d    4.0
b    7.0
dtype: float64


In [67]:
list=[[110,102,183],[140,175,106],[170,195,117],[192,140,195]]

list1=np.array(list).reshape(4,3)

print(list1)

[[110 102 183]
 [140 175 106]
 [170 195 117]
 [192 140 195]]


In [97]:
r1=np.min(list, axis=1)

r1




array([102, 106, 117, 140])

In [99]:
list1[list1 %2!=0]=-2

list1

array([[110, 102,  -2],
       [140,  -2, 106],
       [170,  -2,  -2],
       [192, 140,  -2]])

In [101]:
list1[0,1]=list1[1,0]

list1

array([[110, 140,  -2],
       [140,  -2, 106],
       [170,  -2,  -2],
       [192, 140,  -2]])

In [93]:
# Ask the user to enter a string
user_input = input("Enter a string: ")

# Create an empty dictionary to store character frequencies
char_freq = {}

# Iterate through each character in the string
for char in user_input:
    # Increment the count for each character in the dictionary
    char_freq[char] = char_freq.get(char, 0) + 1

# Print the dictionary
print("Character frequencies:")
# for char, freq in char_freq.items():
#     print(f"'{char}': {freq}")
print(char_freq)

Character frequencies:
{'#': 1, 'a': 4, 'm': 5, 's': 5, '1': 3, '2': 3, '3': 1}
